### ISSUE TITLE
Trouble with auth (Likely copied the wrong thing)

### ISSUE THREAD

**Issue by PaulGWebster** [qaisjp/go-discord-irc#124]
```
$ docker run discordbridge
time="2022-01-15T17:00:51Z" level=info msg="Loading configuration..." ConfigName=config ConfigPath=. ConfigType=yml
time="2022-01-15T17:00:51Z" level=warning msg="webirc_pass is empty"
time="2022-01-15T17:00:51Z" level=info msg="Cooldown duration for IRC puppets is 24h0m0s"
time="2022-01-15T17:00:51Z" level=fatal msg="Go-Discord-IRC failed to start." error="can't open discord: failed to refresh guild webhooks: missing 'Manage Webhooks' permission"
```

I am certain I have the correct discord_token guild_id and effective channel mapping, I did the buil a bot step and copied from 
![image](https://user-images.githubusercontent.com/401142/149628938-bc0b1302-5901-4688-82ad-434d218f2aaa.png)

The correct place .... indeed not sure what the trouble is or what I got wrong!

**Comment by PaulGWebster** [comment]
I am using the following permissions: 
![image](https://user-images.githubusercontent.com/401142/149628963-12f25ef3-89b8-4986-8db2-11ab98c357a6.png)

**Comment by PaulGWebster** [comment]
Ok  I did the auth step again and gave it: permissions=1644906413303 which is in effect everything but administrator, now I get:

```$ ./go-discord-irc --config config.yml
INFO[0000] Loading configuration...                      ConfigName=config ConfigPath=. ConfigType=yml
WARN[0000] webirc_pass is empty
INFO[0000] Cooldown duration for IRC puppets is 24h0m0s
FATA[0000] Go-Discord-IRC failed to start.               error="can't open discord: discord, could not open session: websocket: close 4014: Disallowed intent(s)."
```

**Comment by PaulGWebster** [comment]
ah ha I got it, I needed to enable: 
![image](https://user-images.githubusercontent.com/401142/149629398-3908df20-29f4-4e73-aaec-43cd58218563.png)

... though now:
$ ./go-discord-irc --config config.yml
INFO[0000] Loading configuration...                      ConfigName=config ConfigPath=. ConfigType=yml
WARN[0000] webirc_pass is empty
INFO[0000] Cooldown duration for IRC puppets is 24h0m0s
2022/01/15 17:16:22 Connected to irc.libera.chat:6697 (64.86.243.186:6697)
INFO[0002] Go-Discord-IRC is now running. Press Ctrl-C to exit.
INFO[0009] Listener has joined IRC channel ##daemon.
panic: state cache not found

goroutine 18 [running]:
github.com/qaisjp/go-discord-irc/bridge.(*discordBot).GetAvatar(0xc000203410, 0xc000210180, 0x12, 0xc0001f80c1, 0x6, 0xc00020c900, 0x8)
        /home/paul.webster/Personal/go-discord-irc/bridge/discord.go:418 +0x347
github.com/qaisjp/go-discord-irc/bridge.(*Bridge).loop(0xc0002807e0)
        /home/paul.webster/Personal/go-discord-irc/bridge/bridge.go:385 +0x84e
created by github.com/qaisjp/go-discord-irc/bridge.New
        /home/paul.webster/Personal/go-discord-irc/bridge/bridge.go:260 +0x318

```

**Comment by PaulGWebster** [comment]
Got it, needed to enable all intents
